#! /bin/sh
#
 
FW_UPGD_RST_GPIO=/sys/class/gpio/gpio1_pg4/value
FW_UPGD_RST_EXPORT=/sys/class/gpio/export
FW_UPGD_RST_DIR=/sys/class/gpio/gpio1_pg4/direction
 
 
. /lib/lsb/init-functions
 
check_dev_null() {
     if [ ! -c /dev/null ]; then
         if [ "$1" = log_end_msg ]; then
             log_end_msg 1 || true
         fi
         if ! run_by_init; then
             log_action_msg "/dev/null is not a character device!" || true
         fi
         exit 1
     fi
}
 
case "$1" in
   start)
         check_dev_null
         log_daemon_msg "Starting Zeepro Arcontrol Server" || true
         echo 1 > $FW_UPGD_RST_EXPORT
         echo out > $FW_UPGD_RST_DIR
         echo 0 > $FW_UPGD_RST_GPIO
         if start-stop-daemon --start --quiet --name arcontrold --exec /usr/bin/arcontrold >/var/log/arconrold 2>&1 &
         then
             log_end_msg 0 || true
         else
             log_end_msg 1 || true
         fi
     ;;
   stop)
         log_daemon_msg "Stopping Zeepro Arcontrol Server" || true
         if start-stop-daemon --stop --quiet --oknodo --name arcontrold
         then
             log_end_msg 0 || true
         else
             log_end_msg 1 || true
         fi
         ;;
   *)
     echo "Usage: /etc/init.d/upgrade {start|stop}"
     exit 1
     ;;
esac
 
exit 0
