#!/bin/sh
### BEGIN INIT INFO
# Provides:          netbios
# Required-Start:    $network
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Zeepro netBios service
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin"

# Check that smb.conf exists.
[ -f /etc/samba/smb.conf ] || exit 0

# Make directories.
#mkdir -p /var/cache/samba
#mkdir -p /var/log/samba
#mkdir -p /var/lock/subsys

RETVAL=0

start() {
        echo -n "Starting Zeepro NetBios services: "
        nmbd -i -s /etc/samba/smb.conf &
        RETVAL=$?
        echo "done"

        return $RETVAL
}

stop() {
        echo -n "Shutting down Zeepro NetBios services: "
        kill -9 `pidof nmbd`
        RETVAL=$?
        rm -f /var/run/nmbd-smb2.conf.pid

        echo "done"
        return $RETVAL
}

restart() {
        stop
        start
}

reload() {
        echo -n "Reloading smb.conf file: "
        kill -HUP `pidof smbd`
        RETVAL=$?
        echo "done"
        return $RETVAL
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        restart
        ;;
  reload)
        reload
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload}"
        exit 1
esac

exit $?
