#! /bin/sh

PATH="$PATH:/sbin:/bin:/usr/sbin:/usr/bin"

. /lib/lsb/init-functions

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if [ "$1" = log_end_msg ]; then
            log_end_msg 1 || true
        fi
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

case "$1" in
  start)
        echo "do nothing"
        ;;

  slice)
	check_dev_null
	log_daemon_msg "Starting Zeepro Remote slicing Daemon" || true
	if start-stop-daemon --start --quiet --name remote_slice.sh --exec /usr/lib/zeepro-slic3r/remote_slice.sh -- start "$2" "$3" >/dev/null 2>&1 &
	then
		log_end_msg 0 || true
	else
		log_end_msg 1 || true
	fi
#	/usr/lib/zeepro-slic3r/remote_slice.sh start "$2" "$3" >/dev/null 2>&1 &
	;;
  stop)
	/usr/lib/zeepro-slic3r/remote_slice.sh stop
	;;
  *)
	echo "Usage: /etc/init.d/remote_slice {start|stop|slice}"
	exit 1
	;;
esac

exit 0
