#! /bin/sh

PATH="/sbin:/bin:/usr/sbin"
ZEEPRO_HOSTNAME_FILE=/etc/hostname

. /lib/lsb/init-functions

do_start(){
	zeepro-set-hostname 
	return 0
}

do_stop(){
	return 0
}


case "$1" in
  start)
        log_daemon_msg "Starting Zeepro Hostname" || true
 	do_start         
        log_end_msg 0 || true
    ;;
  stop)
        log_daemon_msg "Stopping Zeepro Hostname" || true
	do_stop
        log_end_msg 0 || true
    ;;
  *)
    echo "Usage: /etc/init.d/zeepro-hostname {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
