#! /bin/sh
### BEGIN INIT INFO
# Provides:          zeepro_statsd
# Required-Start:    $zeepro_network
# Required-Stop:
# Should-Start:
# Default-Start:     S
# Default-Stop:
# Short-Description: Zeepro Statistic Service
### END INIT INFO

. /lib/lsb/init-functions

check_dev_null() {
    if [ ! -c /dev/null ]; then
        if [ "$1" = log_end_msg ]; then
            log_end_msg 1 || true
        fi
        if ! run_by_init; then
            log_action_msg "/dev/null is not a character device!" || true
        fi
        exit 1
    fi
}

case "$1" in
  start)
        check_dev_null
        log_daemon_msg "Starting Zeepro Statistic Daemon" || true
        if start-stop-daemon --start --quiet --name zeepro-stats.sh --exec /usr/bin/zeepro-stats.sh &
        then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  stop)
        log_daemon_msg "Stopping Zeepro Statistic Daemon" || true
        if start-stop-daemon --stop --quiet --oknodo --name zeepro-stats.sh
        then
            log_end_msg 0 || true
        else
            log_end_msg 1 || true
        fi
        ;;
  send)
        /usr/bin/zeepro-stats.sh send $2 &
        ;;
  *)
    echo "Usage: /etc/init.d/zeepro-statsd {start|stop|send}"
    exit 1
    ;;
esac

exit 0
